### ISSUE TITLE
set v-odometer in Laravel5.5

### ISSUE THREAD

**Issue by effedetto** [JefferyHus/v-odometer#4]
Hi , 
how can I include this v-odometer in Laravel5.5 ? 
I'm trying to set main.js-->App.js and index.html -->Odometer.vue , and after I'll register the odometer component,but in npm run watch I have many mistakes . 
do you can Help me , or can tell me how can I Import quickly this item  Please? 
Thanks

**Comment by JefferyHus** [comment]
copy your code here so I can see you issue, also make sure to post the NPM error log

**Comment by effedetto** [comment]
### js/Odometer.vue
`<template>
	<div id="app">
		<vue-odometer :value="mynumber" animation="smooth"></vue-odometer>
		<button @click="updateNumber()">Update</button>
	</div>
</template>

<script>
	import VueOdometer from '../../src'

	export default {
		name: 'app',
		data: function () {
			return {
				mynumber: 0
			}
		},
		methods: {
			updateNumber: function ()
			{
				this.mynumber = Math.floor(Math.random() * (9999 - 1)) + 1
				console.log(this.mynumber)
			}
		},
		components: {
			"vue-odometer": VueOdometer
		}
	}
</script>	`

**Comment by effedetto** [comment]
this is my js/Odometer.vue [https://pastebin.com/GA8gDn93](url)
this is my App.js [https://pastebin.com/eK13n64t](url)
this is my npm Error [https://pastebin.com/4ypakTDv](url)
this is my package.jons [https://pastebin.com/UrwKZTua](url)

**Comment by effedetto** [comment]
`{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.17",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^1.0",
        "lodash": "^4.17.4",
        "vue": "^2.5.7"
    },
    "dependencies": {
        "gulp": "^3.9.1",
        "v-odometer": "^2.0.0"
    }
}
`

**Comment by effedetto** [comment]
this is my project in Laravel5.5 https://github.com/effedetto/stub/

**Comment by JefferyHus** [comment]
use the import like this
```javascript
import VueOdometer from 'vue-odometer/src'
```

**Comment by effedetto** [comment]
this is my new npm error https://pastebin.com/PR02t2q3

**Comment by JefferyHus** [comment]
open your command line and install the package first:
```c
npm install v-odometer --save
```
then inside your template you import it just like this:
```javascript
import VueOdometer from 'v-odometer/src'
```

**Comment by effedetto** [comment]
Thanks , now play right. I have set wrong file.

**Comment by JefferyHus** [comment]
glad it works for you now :+1:
