### ISSUE TITLE
Numbers won't do the count up animation

### ISSUE THREAD

**Issue by sebbler1337** [JefferyHus/v-odometer#8]
Hey,

thanks for the vue-wrapper :)

Just wanted to point out that the "animation" prop shouldn't be count as default. At least mention it somewhere in your readme. I think in the original package it is enabled by default.

Took me a while to figure out why the hell it wouldn't do the count up animation.

Thanks in advance,

Sebastian

**Comment by JefferyHus** [comment]
ah thanks, and great job noticing this 👍 
I will have time tomorrow and will update the wrapper repository.
Cheers

**Comment by JefferyHus** [comment]
[2d94c76](https://github.com/JefferyHus/v-odometer/commit/2e3ac05394e539199d3714ccb8a6815bf5304f89) Properties are added to the bottom of the Read.me file
