### ISSUE TITLE
Odometer is not defined nuxt

### ISSUE THREAD

**Issue by ouahibAbdou** [JefferyHus/v-odometer#9]
Hi I'm using nuxt and I want to use Odometer this the code
`
<template>
<div>
<vue-odometer :value="counter"></vue-odometer>
</div>
</template>
<script>
import VueOdometer from "v-odometer/src";
export default {
  components: {
    "vue-odometer": VueOdometer
  },
  data() {
    return {
      counter: 11222
    };
  }
};
</script>`

**Comment by JefferyHus** [comment]
First you will have to let Nuxt know that `https://github.com/HubSpot/odometer/blob/master/odometer.min.js` is required to be loaded in order for `Odometer` object to be intiated.
This the an [FAQ](https://nuxtjs.org/faq/) from nuxt official website.

**Comment by JefferyHus** [comment]
I am closing this as solved.

**Comment by dse102** [comment]
I'm struggling with this.  I followed the FAQ and added to my nuxt.config file, but it's still not working.

`head: {
    script: [
      { src: 'https://github.com/HubSpot/odometer/blob/master/odometer.min.js' }
    ],`

**Comment by JefferyHus** [comment]
This is more likely related with Nuxt loading scripts into your DOM. For now I am working on a new version which will be independent of odometer library.

**Comment by lexan73** [comment]
> This is more likely related to Nuxt loading scripts into your DOM. For now I am working on a new version which will be independent of odometer library.

https://github.com/xlsdg/vue-odometer/issues/3#issue-353307288

**Comment by JefferyHus** [comment]
https://github.com/JefferyHus/v-odometer/pull/47
